"""
A directive used by the Apollo iOS client to annotate operations or fragments that should be used exclusively for generating local cache mutations instead of as standard operations.
"""
directive @apollo_client_ios_localCacheMutation on QUERY | MUTATION | SUBSCRIPTION | FRAGMENT_DEFINITION

type Query {
  getEvent(id: String!): CalendarEventType!
  getEvents(fromDate: DateTimeType!, toDate: DateTimeType!): [CalendarEventType!]!
  getWalks: [WalkType!]!
  getWalk(id: String!): WalkType!
  getWalkDayActivity(date: DateTimeType!): WalkDayActivity!
  getWalkIntervalActivityByDay(fromDate: DateTimeType!, toDate: DateTimeType!): WalkIntervalActivity!
  me: UserType!
}

type CalendarEventType {
  id: String!
  title: String!
  notes: String!
  startedAt: DateTimeType!
  endedAt: DateTimeType!
  type: CalendarEventTypeEnumType!
}

"""Date with time (isoformat)"""
scalar DateTimeType

enum CalendarEventTypeEnumType {
  walking
  food
  pills
  grooming
  vet
  other
}

type WalkType {
  id: String!
  startedAt: DateTimeType!
  finishedAt: DateTimeType!
  walkHistory: WalkHistoryType!
  distance: Float!
  duration: Float!
  avgSpeed: Float!
  avgPace: Float!
}

type WalkHistoryType {
  history: [WalkHistoryItemType!]!
}

type WalkHistoryItemType {
  latitude: Float!
  longitude: Float!
  timestamp: DateTimeType!
}

type WalkDayActivity {
  totalDistance: Float!
  totalDuration: Float!
  avgSpeed: Float!
  avgPace: Float!
  date: DateTimeType!
}

type WalkIntervalActivity {
  totalDistance: Float!
  totalDuration: Float!
  items: [WalkIntervalActivityItem!]!
}

type WalkIntervalActivityItem {
  date: DateTimeType!
  duration: Float!
}

type UserType {
  id: String!
  name: String!
  dogs: [DogType!]!
}

type DogType {
  id: String!
  name: String!
  breed: String!
  dateOfBirth: DateTimeType!
  sex: String!
}

type Mutation {
  createEvent(input: CreateEventInput!): CalendarEventType!
  createWalk(input: CreateWalkInput!): WalkType!
}

input CreateEventInput {
  title: String!
  notes: String!
  startedAt: DateTimeType!
  endedAt: DateTimeType!
  type: CalendarEventTypeEnumType!
}

input CreateWalkInput {
  startedAt: DateTimeType!
  finishedAt: DateTimeType!
  walkHistory: CreateWalkHistoryType!
}

input CreateWalkHistoryType {
  history: [CreateWalkHistoryItemType!]!
}

input CreateWalkHistoryItemType {
  latitude: Float!
  longitude: Float!
  timestamp: DateTimeType!
}