"""
A directive used by the Apollo iOS client to annotate operations or fragments that should be used exclusively for generating local cache mutations instead of as standard operations.
"""
directive @apollo_client_ios_localCacheMutation on QUERY | MUTATION | SUBSCRIPTION | FRAGMENT_DEFINITION

type Query {
  getEvent(id: String!): CalendarEventType!
  getEvents(fromDate: DateTimeType!, toDate: DateTimeType!): [CalendarEventType!]!
  getWalks(fromDate: DateTimeType = null, toDate: DateTimeType = null, limit: Int = 10): [WalkType!]!
  getWalk(id: String!): WalkType!
  getWalkDayActivity(date: DateTimeType!): WalkDayActivity!
  getWalkIntervalActivityByDay(fromDate: DateTimeType!, toDate: DateTimeType!): WalkIntervalActivity!
  me: UserType!
  getCommunities: [CommunityType!]!
  getCommunity(id: String!): CommunityType!
}

type CalendarEventType {
  id: String!
  title: String!
  notes: String!
  startedAt: DateTimeType!
  endedAt: DateTimeType!
  type: CalendarEventTypeEnumType!
}

"""Date with time (isoformat)"""
scalar DateTimeType

enum CalendarEventTypeEnumType {
  walking
  food
  pills
  grooming
  vet
  other
}

type WalkType {
  id: String!
  startedAt: DateTimeType!
  finishedAt: DateTimeType!
  walkHistory: WalkHistoryType!
  distance: Float!
  duration: Float!
  avgSpeed: Float!
  avgPace: Float!
}

type WalkHistoryType {
  history: [WalkHistoryItemType!]!
}

type WalkHistoryItemType {
  latitude: Float!
  longitude: Float!
  timestamp: DateTimeType!
}

type WalkDayActivity {
  totalDistance: Float!
  totalDuration: Float!
  avgSpeed: Float!
  avgPace: Float!
  date: DateTimeType!
}

type WalkIntervalActivity {
  totalDistance: Float!
  totalDuration: Float!
  items: [WalkIntervalActivityItem!]!
}

type WalkIntervalActivityItem {
  date: DateTimeType!
  duration: Float!
}

type UserType {
  id: String!
  name: String!
  dogs: [DogType!]!
}

type DogType {
  id: String!
  name: String!
  breed: String!
  dateOfBirth: DateTimeType!
  sex: String!
}

type CommunityType {
  id: String!
  name: String!
  owner: UserType!
  members: [CommunityMemberType!]!
  places: [CommunityPlaceType!]!
}

type CommunityMemberType {
  user: UserType!
  lastCheckin: CommunityMemberLastCheckinType
}

type CommunityMemberLastCheckinType {
  date: DateTimeType!
  place: CommunityPlaceType!
}

type CommunityPlaceType {
  id: String!
  name: String!
  lat: Float!
  lon: Float!
}

type Mutation {
  createEvent(input: CreateEventInput!): CalendarEventType!
  createWalk(input: CreateWalkInput!): WalkType!
  setPushToken(token: String!): UserType!
  createCommunity(name: String!): CommunityType!
  createCommunityPlace(input: CommunityPlaceInput!): CommunityType!
  checkinCommunityPlace(communityId: String!, placeId: String!, date: DateTimeType!): CommunityType!
}

input CreateEventInput {
  title: String!
  notes: String!
  startedAt: DateTimeType!
  endedAt: DateTimeType!
  type: CalendarEventTypeEnumType!
}

input CreateWalkInput {
  startedAt: DateTimeType!
  finishedAt: DateTimeType!
  walkHistory: CreateWalkHistoryType!
}

input CreateWalkHistoryType {
  history: [CreateWalkHistoryItemType!]!
}

input CreateWalkHistoryItemType {
  latitude: Float!
  longitude: Float!
  timestamp: DateTimeType!
}

input CommunityPlaceInput {
  communityId: String!
  name: String!
  lat: Float!
  lon: Float!
}